# Generated by Django 4.1.1 on 2022-11-02 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_delete_mainposts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='characteristics',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='datetime',
            new_name='date_posted',
        ),
        migrations.RemoveField(
            model_name='post',
            name='height',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ht',
        ),
    ]
